name: Run JUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo ln -s /usr/bin/chromium-browser /usr/bin/chrome
      
      - name: Run tests with Maven
        env:
          TESTOMAT_API_KEY: ${{ secrets.TESTOMATIO }}
        run: mvn test
      
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            target/screenshots/
            target/videos/
            target/surefire-reports/
      
      - name: Upload to Testomat.io
        uses: actions/upload-artifact@v3
        with:
          name: testomat-results
          path: target/testomat-results/
          retention-days: 7 