# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# - cron: "0 8 * * *"


name: CodeceptJS examples TESTOMATIO reporting

on:
  workflow_dispatch:
    inputs:
      testomatio:
        required: false
      testomatio_url:
        required: false
      run:
        required: false
      browsers:
        required: false
  schedule:
    - cron: "*/30 * * * *"

jobs:
  reporting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Switch to the codeceptJS example dir
      run: cd codeceptJS/
    - name: Dependencies installing
      run: npm i
    - name: Generate unique run value
      id: generate-run
      run: echo "::set-output name=run_value::$(date +%s)"
    - run: npx codeceptjs run"
      env:
        TESTOMATIO: "${{ secrets.TESTOMATIO }}"
        TESTOMATIO_URL: "${{ secrets.TESTOMATIO_URL }}"
        CODECEPT_GROUP_TESTS: "${{ secrets.CODECEPT_GROUP_TESTS }}"
