# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# - cron: "0 8 * * *"
name: CodeceptJS example reporting results

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  reporting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Switch example branch
        run: cd codeceptJS/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Dependencies installing
        run: npm ci
      - name: execute tests
        continue-on-error: true
        run: npx codeceptjs run
        env:
          TESTOMATIO: "${{ secrets.TESTOMATIO }}"
          TESTOMATIO_URL: "${{ secrets.TESTOMATIO_URL }}"
          CODECEPT_GROUP_TESTS: "${{ secrets.CODECEPT_GROUP_TESTS }}"