# used for Testomatio CI functionality testing

name: testomatio-ci-test


on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep'
        required: false
        default: ''
      run:
        required: false
        default: ''
      testomatio:
        required: false
        default: ''


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ci-test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm i

      - run: npx playwright install chromium --with-deps

      - run: npx playwright test --grep "${{ github.event.inputs.grep }}"
        env:
          TESTOMATIO: "${{ github.event.inputs.testomatio }}"
          TESTOMATIO_RUN: "${{ github.event.inputs.run }}"